version: "3.2"

services:
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY="django-insecure-)8u91_v9na14svtric#0i!wysaep)utawy)rr#wgpgydn1ud!@"
      - DEBUG=True

  db:
    image: postgres
      # image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
    